application:
  name: Encrypted Anonymous Note
server:
  # Host should be 0.0.0.0 to listen on all interfaces inside the container,
  # making it accessible via the port mapping from the host.
  host: 0.0.0.0
  port: 3003
  max_file_size_mb: 200 # 新增：默认最大文件上传大小为 15MB
  # allowed_origins: 允许访问 API 的前端来源列表。
  # 在生产环境中，请务必修改为你的前端域名。
  # 如果列表为空或未定义，将不允许任何跨域请求（除非 AllowAllOrigins 在代码中被强制设为 true）。
  allowed_origins:
    - http://localhost:3003 # 本地开发环境
    - http://127.0.0.1:3003 # 本地开发环境
    # - https://your-frontend-domain.com # 生产环境前端域名
paths: # Corrected indentation
  # 存储元数据 JSON 文件的目录 (相对于 /app)
  data_storage_dir: storage/data
  # 存储最终合并文件的目录 (相对于 /app)
  final_upload_dir: uploads
  # 存储临时分片的目录 (相对于 /app)
  temp_chunk_dir: temp-files
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console: {}
    file:
      # Path relative to the application's working directory (/app)
      path: logs/application.log

# Database section removed

expiration:
  enabled: true             # 是否启用有效期功能 (true/false)
  mode: "free"              # 模式: "forced" (强制使用默认值) 或 "free" (用户可选)
  default_duration: "24h"   # 默认有效期 (例如 "1h", "24h", "168h" for 1 week)
  available_durations:      # 用户可选的有效期列表 (仅在 mode="free" 时有效)
    - "1h"
    - "24h"
    - "72h"  # 3 days
    - "168h" # 1 week

  # 访问窗口配置 (可选, 用于在主有效期内限制首次访问后的时间)
  access_window:
    enabled: false            # 是否启用访问窗口 (true/false)
    default_duration: "10m" # 默认访问窗口期 (例如 "5m", "1h")
    rules:                  # 基于文件类型或大小的动态访问窗口规则 (可选)
      - type: ["jpg", "png", "gif"]
        duration: "5m"
      - type: ["mp4", "mov"]
        min_size_mb: 100
        duration: "30m"
      - type: ["txt", "pdf"]
        max_size_mb: 50
        duration: "1h"
      - type: ["zip", "tar"]
        min_size_mb: 200
        max_size_mb: 500
        duration: "2h"
      - type: ["doc", "docx"]
        duration: "1h"
      - type: ["xls", "xlsx"]
        duration: "1h"
      - type: ["ppt", "pptx"]
        duration: "1h"  
      - type: ["mp3", "wav"]
        duration: "1h"  
      - type: ["avi", "mkv"]
        duration: "1h"
      - type: ["exe", "bin"]
        duration: "1h"
      - type: ["iso"]
        duration: "1h"
      - type: ["json", "xml"]
        duration: "1h"
      - type: ["csv"]
        duration: "1h"
      - type: ["html", "htm"]
        duration: "1h"
      - type: ["md"]
        duration: "1h"
      - type: ["log"]
        duration: "1h"
      - type: ["mp4", "mov"]
        min_size_mb: 100
        duration: "30m"
      - type: ["txt", "pdf"]
        max_size_mb: 50
        duration: "1h"
      - type: ["zip", "tar"]
        min_size_mb: 200
        max_size_mb: 500
        duration: "2h"
      - type: ["doc", "docx"]
        duration: "1h"
      - type: ["xls", "xlsx"]
        duration: "1h"
      - type: ["ppt", "pptx"]
        duration: "1h"
      - type: ["mp3", "wav"]
        duration: "1h"



