services:
  biu_email:
    # Use the pre-built image from GHCR instead of building locally
    image: ghcr.io/jacksunhack/biu_email:main # Changed from build: directive
    container_name: biu_email
    restart: unless-stopped
    volumes:
      # Mount the configuration file (read-only recommended)
      # Ensure ./config.yaml exists on your host machine
      - ./config.yaml:/app/config.yaml:ro

      # Mount directories for persistent data
      # IMPORTANT: Ensure these directories exist on your host machine
      # AND have the correct permissions for the user inside the container!
      - ./biu_email_data/messages:/app/messages:rw
      - ./biu_email_data/temp-files:/app/temp-files:rw # Added :rw for consistency, adjust if needed
      - ./biu_email_data/logs:/app/logs:rw             # Added :rw for consistency, adjust if needed
      - ./biu_email_data/storage:/app/storage:rw

      # Optional: If the application needs to write a DB file directly in /app
      # - ./biu_email_data/biu_email.db:/app/biu_email.db:rw # Example if db is separate

    ports:
      # Map host port 3003 to container port 3003 (defined in config.yaml and exposed in Dockerfile)
      - "3003:3003"

    # If you need to run as a specific host user to match volume permissions:
    # user: "YOUR_HOST_UID:YOUR_HOST_GID" # Replace with the UID/GID owning ./biu_email_data

    # Optional: Define a network if needed
    # networks:
    #   - biu_network

# Optional: Define networks if used
# networks:
#   biu_network:
#     driver: bridge