# GitHub Actions 配置文件
# Docker镜像相关配置
docker:
  registry: ghcr.io
  # 镜像名称将自动使用 github.repository
  image_tags:
    - latest
    - ${GITHUB_SHA::8}  # 提交的短SHA
    - ${GITHUB_REF##*/} # 分支名或标签名

# Go编译相关配置
go:
  version: '1.21'
  build_flags: '-v'
  platforms:
    - GOOS: linux
      GOARCH: amd64
    - GOOS: linux
      GOARCH: arm64
    - GOOS: windows
      GOARCH: amd64

# Release配置
release:
  # Debian包配置
  debian:
    package_name: biu-email
    maintainer: "Your Name <your.email@example.com>"
    description: "Secure file sharing with end-to-end encryption"
    section: utils
    priority: optional
    
  # Release配置
  github:
    draft: false
    prerelease: false
    generate_notes: true