name: Release and Docker Push

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

env:
  IMAGE_NAME: biu_email
  # DOCKER_HUB_USERNAME and DOCKER_HUB_TOKEN are now correctly referenced via secrets directly where needed

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # --- Add permissions block here ---
    permissions:
      contents: read    # Needed for actions/checkout
      packages: write   # Needed to push docker image to GHCR
    # ----------------------------------
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]; then
            echo "::error::DOCKER_HUB_USERNAME secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DOCKER_HUB_TOKEN }}" ]; then
            echo "::error::DOCKER_HUB_TOKEN secret is not set"
            exit 1
          fi
          echo "Secrets validation passed"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use github.actor or github.repository_owner
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }} # Use github.repository_owner

      # --- Combine Build and Push step ---
      - name: Build and push to Docker Hub and GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Push is enabled
          tags: ${{ steps.meta.outputs.tags }} # Use ALL generated tags
          labels: ${{ steps.meta.outputs.labels }} # Use generated labels
      # --- Removed the separate GHCR push step ---

  create-release:
    name: Create Release
    needs: build-and-push
    runs-on: ubuntu-latest
    # --- Add permissions block here too ---
    # Need contents: write to create a release
    permissions:
      contents: write
    # ------------------------------------
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout is still needed to get the tag info

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Automated release for ${{ github.ref_name }}
            Docker images pushed to:
            - Docker Hub: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
            - GitHub Packages: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }} # Use github.repository_owner
          draft: false
          prerelease: false
        # env: # GITHUB_TOKEN is automatically used by softprops/action-gh-release
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This line is usually not needed
